// Implementation file for parser generated by fsyacc
module AlgoMoveTranspiler.Parser
#nowarn "64";; // turn off warnings that type variables used in production annotations are instantiated to concrete type
open FSharp.Text.Lexing
open FSharp.Text.Parsing.ParseHelpers
# 1 "Parser.fsy"


open AlgoMoveTranspiler.Absyn

open FSharp.Common
open FSharp.Common.Parsing.LexYacc
open AlgoMoveTranspiler 
open AlgoMoveTranspiler.Absyn

let parse_error_rich = Some (fun ctx -> raise (ParseErrorContextException ctx))


# 19 "Parser.fs"
// This type is the type of tokens accepted by the parser
type token = 
  | EOF
  | MODULE
  | STRUCT
  | HAS
  | COPY
  | DROP
  | KEY
  | STORE
  | PUBLIC
  | ENTRY
  | TU64
  | TBOOL
  | TADDRESS
  | BRA
  | KET
  | SQBRA
  | SQKET
  | CURBRA
  | CURKET
  | COLON
  | SEMICOLON
  | DOT
  | COMMA
  | MOVLOC
  | CPYLOC
  | STLOC
  | ID of (System.String)
  | UINT64 of (System.UInt64)
// This type is used to give symbolic names to token indexes, useful for error messages
type tokenId = 
    | TOKEN_EOF
    | TOKEN_MODULE
    | TOKEN_STRUCT
    | TOKEN_HAS
    | TOKEN_COPY
    | TOKEN_DROP
    | TOKEN_KEY
    | TOKEN_STORE
    | TOKEN_PUBLIC
    | TOKEN_ENTRY
    | TOKEN_TU64
    | TOKEN_TBOOL
    | TOKEN_TADDRESS
    | TOKEN_BRA
    | TOKEN_KET
    | TOKEN_SQBRA
    | TOKEN_SQKET
    | TOKEN_CURBRA
    | TOKEN_CURKET
    | TOKEN_COLON
    | TOKEN_SEMICOLON
    | TOKEN_DOT
    | TOKEN_COMMA
    | TOKEN_MOVLOC
    | TOKEN_CPYLOC
    | TOKEN_STLOC
    | TOKEN_ID
    | TOKEN_UINT64
    | TOKEN_end_of_input
    | TOKEN_error
// This type is used to give symbolic names to token indexes, useful for error messages
type nonTerminalId = 
    | NONTERM__startmodulee
    | NONTERM_modulee
    | NONTERM_structs
    | NONTERM_structt
    | NONTERM_fields
    | NONTERM_funs
    | NONTERM_funn
    | NONTERM_skiploc
    | NONTERM_skiplocs
    | NONTERM_arg
    | NONTERM_args
    | NONTERM_instr
    | NONTERM_instrs
    | NONTERM_quals
    | NONTERM_qual
    | NONTERM_return_ty
    | NONTERM_ty
    | NONTERM_capabs
    | NONTERM_capab
    | NONTERM_qid
    | NONTERM_label
    | NONTERM_loc
    | NONTERM_opcode

// This function maps tokens to integer indexes
let tagOfToken (t:token) = 
  match t with
  | EOF  -> 0 
  | MODULE  -> 1 
  | STRUCT  -> 2 
  | HAS  -> 3 
  | COPY  -> 4 
  | DROP  -> 5 
  | KEY  -> 6 
  | STORE  -> 7 
  | PUBLIC  -> 8 
  | ENTRY  -> 9 
  | TU64  -> 10 
  | TBOOL  -> 11 
  | TADDRESS  -> 12 
  | BRA  -> 13 
  | KET  -> 14 
  | SQBRA  -> 15 
  | SQKET  -> 16 
  | CURBRA  -> 17 
  | CURKET  -> 18 
  | COLON  -> 19 
  | SEMICOLON  -> 20 
  | DOT  -> 21 
  | COMMA  -> 22 
  | MOVLOC  -> 23 
  | CPYLOC  -> 24 
  | STLOC  -> 25 
  | ID _ -> 26 
  | UINT64 _ -> 27 

// This function maps integer indexes to symbolic token ids
let tokenTagToTokenId (tokenIdx:int) = 
  match tokenIdx with
  | 0 -> TOKEN_EOF 
  | 1 -> TOKEN_MODULE 
  | 2 -> TOKEN_STRUCT 
  | 3 -> TOKEN_HAS 
  | 4 -> TOKEN_COPY 
  | 5 -> TOKEN_DROP 
  | 6 -> TOKEN_KEY 
  | 7 -> TOKEN_STORE 
  | 8 -> TOKEN_PUBLIC 
  | 9 -> TOKEN_ENTRY 
  | 10 -> TOKEN_TU64 
  | 11 -> TOKEN_TBOOL 
  | 12 -> TOKEN_TADDRESS 
  | 13 -> TOKEN_BRA 
  | 14 -> TOKEN_KET 
  | 15 -> TOKEN_SQBRA 
  | 16 -> TOKEN_SQKET 
  | 17 -> TOKEN_CURBRA 
  | 18 -> TOKEN_CURKET 
  | 19 -> TOKEN_COLON 
  | 20 -> TOKEN_SEMICOLON 
  | 21 -> TOKEN_DOT 
  | 22 -> TOKEN_COMMA 
  | 23 -> TOKEN_MOVLOC 
  | 24 -> TOKEN_CPYLOC 
  | 25 -> TOKEN_STLOC 
  | 26 -> TOKEN_ID 
  | 27 -> TOKEN_UINT64 
  | 30 -> TOKEN_end_of_input
  | 28 -> TOKEN_error
  | _ -> failwith "tokenTagToTokenId: bad token"

/// This function maps production indexes returned in syntax errors to strings representing the non terminal that would be produced by that production
let prodIdxToNonTerminal (prodIdx:int) = 
  match prodIdx with
    | 0 -> NONTERM__startmodulee 
    | 1 -> NONTERM_modulee 
    | 2 -> NONTERM_structs 
    | 3 -> NONTERM_structs 
    | 4 -> NONTERM_structs 
    | 5 -> NONTERM_structt 
    | 6 -> NONTERM_structt 
    | 7 -> NONTERM_fields 
    | 8 -> NONTERM_funs 
    | 9 -> NONTERM_funs 
    | 10 -> NONTERM_funs 
    | 11 -> NONTERM_funn 
    | 12 -> NONTERM_skiploc 
    | 13 -> NONTERM_skiplocs 
    | 14 -> NONTERM_skiplocs 
    | 15 -> NONTERM_skiplocs 
    | 16 -> NONTERM_arg 
    | 17 -> NONTERM_args 
    | 18 -> NONTERM_args 
    | 19 -> NONTERM_args 
    | 20 -> NONTERM_instr 
    | 21 -> NONTERM_instrs 
    | 22 -> NONTERM_instrs 
    | 23 -> NONTERM_instrs 
    | 24 -> NONTERM_quals 
    | 25 -> NONTERM_quals 
    | 26 -> NONTERM_qual 
    | 27 -> NONTERM_qual 
    | 28 -> NONTERM_return_ty 
    | 29 -> NONTERM_return_ty 
    | 30 -> NONTERM_ty 
    | 31 -> NONTERM_ty 
    | 32 -> NONTERM_ty 
    | 33 -> NONTERM_capabs 
    | 34 -> NONTERM_capabs 
    | 35 -> NONTERM_capab 
    | 36 -> NONTERM_capab 
    | 37 -> NONTERM_capab 
    | 38 -> NONTERM_capab 
    | 39 -> NONTERM_qid 
    | 40 -> NONTERM_qid 
    | 41 -> NONTERM_label 
    | 42 -> NONTERM_loc 
    | 43 -> NONTERM_opcode 
    | 44 -> NONTERM_opcode 
    | 45 -> NONTERM_opcode 
    | _ -> failwith "prodIdxToNonTerminal: bad production index"

let _fsyacc_endOfInputTag = 30 
let _fsyacc_tagOfErrorTerminal = 28

// This function gets the name of a token as a string
let token_to_string (t:token) = 
  match t with 
  | EOF  -> "EOF" 
  | MODULE  -> "MODULE" 
  | STRUCT  -> "STRUCT" 
  | HAS  -> "HAS" 
  | COPY  -> "COPY" 
  | DROP  -> "DROP" 
  | KEY  -> "KEY" 
  | STORE  -> "STORE" 
  | PUBLIC  -> "PUBLIC" 
  | ENTRY  -> "ENTRY" 
  | TU64  -> "TU64" 
  | TBOOL  -> "TBOOL" 
  | TADDRESS  -> "TADDRESS" 
  | BRA  -> "BRA" 
  | KET  -> "KET" 
  | SQBRA  -> "SQBRA" 
  | SQKET  -> "SQKET" 
  | CURBRA  -> "CURBRA" 
  | CURKET  -> "CURKET" 
  | COLON  -> "COLON" 
  | SEMICOLON  -> "SEMICOLON" 
  | DOT  -> "DOT" 
  | COMMA  -> "COMMA" 
  | MOVLOC  -> "MOVLOC" 
  | CPYLOC  -> "CPYLOC" 
  | STLOC  -> "STLOC" 
  | ID _ -> "ID" 
  | UINT64 _ -> "UINT64" 

// This function gets the data carried by a token as an object
let _fsyacc_dataOfToken (t:token) = 
  match t with 
  | EOF  -> (null : System.Object) 
  | MODULE  -> (null : System.Object) 
  | STRUCT  -> (null : System.Object) 
  | HAS  -> (null : System.Object) 
  | COPY  -> (null : System.Object) 
  | DROP  -> (null : System.Object) 
  | KEY  -> (null : System.Object) 
  | STORE  -> (null : System.Object) 
  | PUBLIC  -> (null : System.Object) 
  | ENTRY  -> (null : System.Object) 
  | TU64  -> (null : System.Object) 
  | TBOOL  -> (null : System.Object) 
  | TADDRESS  -> (null : System.Object) 
  | BRA  -> (null : System.Object) 
  | KET  -> (null : System.Object) 
  | SQBRA  -> (null : System.Object) 
  | SQKET  -> (null : System.Object) 
  | CURBRA  -> (null : System.Object) 
  | CURKET  -> (null : System.Object) 
  | COLON  -> (null : System.Object) 
  | SEMICOLON  -> (null : System.Object) 
  | DOT  -> (null : System.Object) 
  | COMMA  -> (null : System.Object) 
  | MOVLOC  -> (null : System.Object) 
  | CPYLOC  -> (null : System.Object) 
  | STLOC  -> (null : System.Object) 
  | ID _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | UINT64 _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
let _fsyacc_gotos = [| 0us;65535us;1us;65535us;0us;1us;2us;65535us;4us;5us;9us;10us;2us;65535us;4us;9us;9us;9us;2us;65535us;13us;14us;18us;19us;2us;65535us;5us;6us;22us;23us;2us;65535us;5us;22us;22us;22us;2us;65535us;30us;38us;39us;38us;2us;65535us;30us;31us;39us;40us;7us;65535us;13us;44us;18us;44us;26us;44us;45us;44us;77us;44us;84us;44us;91us;44us;7us;65535us;13us;21us;18us;21us;26us;27us;45us;46us;77us;78us;84us;85us;91us;92us;2us;65535us;31us;50us;50us;50us;2us;65535us;31us;32us;50us;51us;3us;65535us;5us;24us;22us;24us;52us;53us;3us;65535us;5us;52us;22us;52us;52us;52us;1us;65535us;28us;29us;3us;65535us;36us;37us;42us;43us;56us;57us;2us;65535us;16us;17us;62us;63us;2us;65535us;16us;61us;62us;61us;2us;65535us;2us;3us;69us;70us;4us;65535us;30us;34us;31us;47us;39us;34us;50us;47us;3us;65535us;74us;75us;81us;82us;88us;89us;1us;65535us;48us;49us;|]
let _fsyacc_sparseGotoTableRowOffsets = [|0us;1us;3us;6us;9us;12us;15us;18us;21us;24us;32us;40us;43us;46us;50us;54us;56us;60us;63us;66us;69us;74us;78us;|]
let _fsyacc_stateToProdIdxsTableElements = [| 1us;0us;1us;0us;1us;1us;1us;1us;1us;1us;1us;1us;1us;1us;1us;1us;1us;1us;2us;2us;4us;1us;4us;2us;5us;6us;2us;5us;6us;1us;5us;1us;5us;1us;5us;1us;6us;1us;6us;1us;6us;1us;6us;1us;6us;1us;7us;2us;8us;10us;1us;10us;1us;11us;1us;11us;1us;11us;1us;11us;1us;11us;1us;11us;1us;11us;1us;11us;1us;11us;1us;11us;1us;12us;1us;12us;1us;12us;1us;12us;2us;13us;15us;1us;15us;1us;15us;1us;16us;1us;16us;1us;16us;2us;17us;19us;1us;19us;1us;19us;1us;20us;1us;20us;1us;20us;2us;21us;23us;1us;23us;2us;24us;25us;1us;25us;1us;26us;1us;27us;1us;28us;1us;28us;1us;30us;1us;31us;1us;32us;2us;33us;34us;1us;34us;1us;34us;1us;35us;1us;36us;1us;37us;1us;38us;2us;39us;40us;1us;40us;1us;40us;1us;41us;1us;42us;1us;43us;1us;43us;1us;43us;1us;43us;1us;43us;1us;43us;1us;43us;1us;44us;1us;44us;1us;44us;1us;44us;1us;44us;1us;44us;1us;44us;1us;45us;1us;45us;1us;45us;1us;45us;1us;45us;1us;45us;1us;45us;|]
let _fsyacc_stateToProdIdxsTableRowOffsets = [|0us;2us;4us;6us;8us;10us;12us;14us;16us;18us;21us;23us;26us;29us;31us;33us;35us;37us;39us;41us;43us;45us;47us;50us;52us;54us;56us;58us;60us;62us;64us;66us;68us;70us;72us;74us;76us;78us;80us;83us;85us;87us;89us;91us;93us;96us;98us;100us;102us;104us;106us;109us;111us;114us;116us;118us;120us;122us;124us;126us;128us;130us;133us;135us;137us;139us;141us;143us;145us;148us;150us;152us;154us;156us;158us;160us;162us;164us;166us;168us;170us;172us;174us;176us;178us;180us;182us;184us;186us;188us;190us;192us;194us;196us;|]
let _fsyacc_action_rows = 94
let _fsyacc_actionTableElements = [|1us;32768us;1us;2us;0us;49152us;1us;32768us;26us;68us;1us;32768us;17us;4us;1us;16387us;2us;11us;2us;16393us;8us;54us;9us;55us;1us;32768us;18us;7us;1us;32768us;0us;8us;0us;16385us;1us;16386us;2us;11us;0us;16388us;1us;32768us;26us;12us;2us;32768us;3us;16us;17us;13us;1us;16402us;26us;41us;1us;32768us;18us;15us;0us;16389us;4us;32768us;4us;64us;5us;65us;6us;66us;7us;67us;1us;32768us;17us;18us;1us;16402us;26us;41us;1us;32768us;18us;20us;0us;16390us;0us;16391us;2us;16392us;8us;54us;9us;55us;0us;16394us;1us;32768us;26us;25us;1us;32768us;13us;26us;1us;16402us;26us;41us;1us;32768us;14us;28us;1us;16413us;19us;56us;1us;32768us;17us;30us;1us;16398us;26us;71us;1us;16406us;26us;71us;1us;32768us;18us;33us;0us;16395us;1us;32768us;19us;35us;1us;32768us;26us;36us;3us;32768us;10us;58us;11us;59us;12us;60us;0us;16396us;1us;16397us;20us;39us;1us;16398us;26us;71us;0us;16399us;1us;32768us;19us;42us;3us;32768us;10us;58us;11us;59us;12us;60us;0us;16400us;1us;16401us;22us;45us;1us;16402us;26us;41us;0us;16403us;1us;32768us;19us;48us;3us;32768us;23us;73us;24us;80us;25us;87us;0us;16404us;1us;16405us;26us;71us;0us;16407us;2us;16408us;8us;54us;9us;55us;0us;16409us;0us;16410us;0us;16411us;3us;32768us;10us;58us;11us;59us;12us;60us;0us;16412us;0us;16414us;0us;16415us;0us;16416us;1us;16417us;22us;62us;4us;32768us;4us;64us;5us;65us;6us;66us;7us;67us;0us;16418us;0us;16419us;0us;16420us;0us;16421us;0us;16422us;1us;16423us;21us;69us;1us;32768us;26us;68us;0us;16424us;0us;16425us;0us;16426us;1us;32768us;15us;74us;1us;32768us;27us;72us;1us;32768us;16us;76us;1us;32768us;13us;77us;1us;16402us;26us;41us;1us;32768us;14us;79us;0us;16427us;1us;32768us;15us;81us;1us;32768us;27us;72us;1us;32768us;16us;83us;1us;32768us;13us;84us;1us;16402us;26us;41us;1us;32768us;14us;86us;0us;16428us;1us;32768us;15us;88us;1us;32768us;27us;72us;1us;32768us;16us;90us;1us;32768us;13us;91us;1us;16402us;26us;41us;1us;32768us;14us;93us;0us;16429us;|]
let _fsyacc_actionTableRowOffsets = [|0us;2us;3us;5us;7us;9us;12us;14us;16us;17us;19us;20us;22us;25us;27us;29us;30us;35us;37us;39us;41us;42us;43us;46us;47us;49us;51us;53us;55us;57us;59us;61us;63us;65us;66us;68us;70us;74us;75us;77us;79us;80us;82us;86us;87us;89us;91us;92us;94us;98us;99us;101us;102us;105us;106us;107us;108us;112us;113us;114us;115us;116us;118us;123us;124us;125us;126us;127us;128us;130us;132us;133us;134us;135us;137us;139us;141us;143us;145us;147us;148us;150us;152us;154us;156us;158us;160us;161us;163us;165us;167us;169us;171us;173us;|]
let _fsyacc_reductionSymbolCounts = [|1us;7us;1us;0us;2us;5us;7us;1us;1us;0us;2us;10us;4us;1us;0us;3us;3us;1us;0us;3us;3us;1us;0us;2us;1us;2us;1us;1us;2us;0us;1us;1us;1us;1us;3us;1us;1us;1us;1us;1us;3us;1us;1us;7us;7us;7us;|]
let _fsyacc_productionToNonTerminalTable = [|0us;1us;2us;2us;2us;3us;3us;4us;5us;5us;5us;6us;7us;8us;8us;8us;9us;10us;10us;10us;11us;12us;12us;12us;13us;13us;14us;14us;15us;15us;16us;16us;16us;17us;17us;18us;18us;18us;18us;19us;19us;20us;21us;22us;22us;22us;|]
let _fsyacc_immediateActions = [|65535us;49152us;65535us;65535us;65535us;65535us;65535us;65535us;16385us;65535us;16388us;65535us;65535us;65535us;65535us;16389us;65535us;65535us;65535us;65535us;16390us;16391us;65535us;16394us;65535us;65535us;65535us;65535us;65535us;65535us;65535us;65535us;65535us;16395us;65535us;65535us;65535us;16396us;65535us;65535us;16399us;65535us;65535us;16400us;65535us;65535us;16403us;65535us;65535us;16404us;65535us;16407us;65535us;16409us;16410us;16411us;65535us;16412us;16414us;16415us;16416us;65535us;65535us;16418us;16419us;16420us;16421us;16422us;65535us;65535us;16424us;16425us;16426us;65535us;65535us;65535us;65535us;65535us;65535us;16427us;65535us;65535us;65535us;65535us;65535us;65535us;16428us;65535us;65535us;65535us;65535us;65535us;65535us;16429us;|]
let _fsyacc_reductions = lazy [|
# 303 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?>  AlgoMoveTranspiler.Absyn.Module  in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                      raise (FSharp.Text.Parsing.Accept(Microsoft.FSharp.Core.Operators.box _1))
                   )
                 : 'gentype__startmodulee));
# 312 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = parseState.GetInput(2) :?> 'gentype_qid in
            let _4 = parseState.GetInput(4) :?> 'gentype_structs in
            let _5 = parseState.GetInput(5) :?> 'gentype_funs in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 35 "Parser.fsy"
                                                       { qid = _2; structs = _4; funs = _5 } 
                   )
# 35 "Parser.fsy"
                 :  AlgoMoveTranspiler.Absyn.Module ));
# 325 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_structt in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 38 "Parser.fsy"
                                                       [_1] 
                   )
# 38 "Parser.fsy"
                 : 'gentype_structs));
# 336 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 39 "Parser.fsy"
                                                       [] 
                   )
# 39 "Parser.fsy"
                 : 'gentype_structs));
# 346 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_structt in
            let _2 = parseState.GetInput(2) :?> 'gentype_structs in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 40 "Parser.fsy"
                                                       _1 :: _2 
                   )
# 40 "Parser.fsy"
                 : 'gentype_structs));
# 358 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = parseState.GetInput(2) :?> System.String in
            let _4 = parseState.GetInput(4) :?> 'gentype_fields in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 44 "Parser.fsy"
                                                       { id = _2; capabs = []; fields = _4 } 
                   )
# 44 "Parser.fsy"
                 : 'gentype_structt));
# 370 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = parseState.GetInput(2) :?> System.String in
            let _4 = parseState.GetInput(4) :?> 'gentype_capabs in
            let _6 = parseState.GetInput(6) :?> 'gentype_fields in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 47 "Parser.fsy"
                                                       { id = _2; capabs = _4; fields = _6 } 
                   )
# 47 "Parser.fsy"
                 : 'gentype_structt));
# 383 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_args in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 50 "Parser.fsy"
                                                       _1 
                   )
# 50 "Parser.fsy"
                 : 'gentype_fields));
# 394 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_funn in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 53 "Parser.fsy"
                                                        [_1] 
                   )
# 53 "Parser.fsy"
                 : 'gentype_funs));
# 405 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 54 "Parser.fsy"
                                                        [] 
                   )
# 54 "Parser.fsy"
                 : 'gentype_funs));
# 415 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_funn in
            let _2 = parseState.GetInput(2) :?> 'gentype_funs in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 55 "Parser.fsy"
                                                        _1 :: _2 
                   )
# 55 "Parser.fsy"
                 : 'gentype_funs));
# 427 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_quals in
            let _2 = parseState.GetInput(2) :?> System.String in
            let _4 = parseState.GetInput(4) :?> 'gentype_args in
            let _6 = parseState.GetInput(6) :?> 'gentype_return_ty in
            let _8 = parseState.GetInput(8) :?> 'gentype_skiplocs in
            let _9 = parseState.GetInput(9) :?> 'gentype_instrs in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 61 "Parser.fsy"
                                                       { quals = _1; id = _2; args = _4; ret = _6; body = _9 } 
                   )
# 61 "Parser.fsy"
                 : 'gentype_funn));
# 443 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_label in
            let _3 = parseState.GetInput(3) :?> System.String in
            let _4 = parseState.GetInput(4) :?> 'gentype_ty in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 64 "Parser.fsy"
                                                      
                   )
# 64 "Parser.fsy"
                 : 'gentype_skiploc));
# 456 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_skiploc in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 67 "Parser.fsy"
                                                       [_1] 
                   )
# 67 "Parser.fsy"
                 : 'gentype_skiplocs));
# 467 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 68 "Parser.fsy"
                                                       [] 
                   )
# 68 "Parser.fsy"
                 : 'gentype_skiplocs));
# 477 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_skiploc in
            let _3 = parseState.GetInput(3) :?> 'gentype_skiplocs in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 69 "Parser.fsy"
                                                       _1 :: _3 
                   )
# 69 "Parser.fsy"
                 : 'gentype_skiplocs));
# 489 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> System.String in
            let _3 = parseState.GetInput(3) :?> 'gentype_ty in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 72 "Parser.fsy"
                                                       _1, _3 
                   )
# 72 "Parser.fsy"
                 : 'gentype_arg));
# 501 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_arg in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 75 "Parser.fsy"
                                                       [_1] 
                   )
# 75 "Parser.fsy"
                 : 'gentype_args));
# 512 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 76 "Parser.fsy"
                                                       [] 
                   )
# 76 "Parser.fsy"
                 : 'gentype_args));
# 522 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_arg in
            let _3 = parseState.GetInput(3) :?> 'gentype_args in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 77 "Parser.fsy"
                                                       _1 :: _3 
                   )
# 77 "Parser.fsy"
                 : 'gentype_args));
# 534 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_label in
            let _3 = parseState.GetInput(3) :?> 'gentype_opcode in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 80 "Parser.fsy"
                                                       _1, _3 
                   )
# 80 "Parser.fsy"
                 : 'gentype_instr));
# 546 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_instr in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 83 "Parser.fsy"
                                                       [_1] 
                   )
# 83 "Parser.fsy"
                 : 'gentype_instrs));
# 557 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 84 "Parser.fsy"
                                                       [] 
                   )
# 84 "Parser.fsy"
                 : 'gentype_instrs));
# 567 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_instr in
            let _2 = parseState.GetInput(2) :?> 'gentype_instrs in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 85 "Parser.fsy"
                                                       _1 :: _2 
                   )
# 85 "Parser.fsy"
                 : 'gentype_instrs));
# 579 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_qual in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 88 "Parser.fsy"
                                                       [_1] 
                   )
# 88 "Parser.fsy"
                 : 'gentype_quals));
# 590 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_qual in
            let _2 = parseState.GetInput(2) :?> 'gentype_quals in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 89 "Parser.fsy"
                                                       _1 :: _2 
                   )
# 89 "Parser.fsy"
                 : 'gentype_quals));
# 602 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 92 "Parser.fsy"
                                                       Public 
                   )
# 92 "Parser.fsy"
                 : 'gentype_qual));
# 612 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 93 "Parser.fsy"
                                                       Entry 
                   )
# 93 "Parser.fsy"
                 : 'gentype_qual));
# 622 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = parseState.GetInput(2) :?> 'gentype_ty in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 96 "Parser.fsy"
                                                       Some _2 
                   )
# 96 "Parser.fsy"
                 : 'gentype_return_ty));
# 633 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 97 "Parser.fsy"
                                                       None 
                   )
# 97 "Parser.fsy"
                 : 'gentype_return_ty));
# 643 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 100 "Parser.fsy"
                                                       U64 
                   )
# 100 "Parser.fsy"
                 : 'gentype_ty));
# 653 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 101 "Parser.fsy"
                                                       Bool 
                   )
# 101 "Parser.fsy"
                 : 'gentype_ty));
# 663 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 102 "Parser.fsy"
                                                       Address 
                   )
# 102 "Parser.fsy"
                 : 'gentype_ty));
# 673 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_capab in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 105 "Parser.fsy"
                                                       [_1] 
                   )
# 105 "Parser.fsy"
                 : 'gentype_capabs));
# 684 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_capab in
            let _3 = parseState.GetInput(3) :?> 'gentype_capabs in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 106 "Parser.fsy"
                                                       _1 :: _3 
                   )
# 106 "Parser.fsy"
                 : 'gentype_capabs));
# 696 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 109 "Parser.fsy"
                                                       Copy 
                   )
# 109 "Parser.fsy"
                 : 'gentype_capab));
# 706 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 110 "Parser.fsy"
                                                       Drop 
                   )
# 110 "Parser.fsy"
                 : 'gentype_capab));
# 716 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 111 "Parser.fsy"
                                                       Key 
                   )
# 111 "Parser.fsy"
                 : 'gentype_capab));
# 726 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 112 "Parser.fsy"
                                                       Store 
                   )
# 112 "Parser.fsy"
                 : 'gentype_capab));
# 736 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> System.String in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 115 "Parser.fsy"
                                                       [_1] 
                   )
# 115 "Parser.fsy"
                 : 'gentype_qid));
# 747 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> System.String in
            let _3 = parseState.GetInput(3) :?> 'gentype_qid in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 116 "Parser.fsy"
                                                       _1 :: _3 
                   )
# 116 "Parser.fsy"
                 : 'gentype_qid));
# 759 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> System.String in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 119 "Parser.fsy"
                                                       _1 
                   )
# 119 "Parser.fsy"
                 : 'gentype_label));
# 770 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> System.UInt64 in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 122 "Parser.fsy"
                                                       _1 
                   )
# 122 "Parser.fsy"
                 : 'gentype_loc));
# 781 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _3 = parseState.GetInput(3) :?> 'gentype_loc in
            let _6 = parseState.GetInput(6) :?> 'gentype_args in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 126 "Parser.fsy"
                                                       MovLoc _3 
                   )
# 126 "Parser.fsy"
                 : 'gentype_opcode));
# 793 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _3 = parseState.GetInput(3) :?> 'gentype_loc in
            let _6 = parseState.GetInput(6) :?> 'gentype_args in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 128 "Parser.fsy"
                                                       CpyLoc _3 
                   )
# 128 "Parser.fsy"
                 : 'gentype_opcode));
# 805 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _3 = parseState.GetInput(3) :?> 'gentype_loc in
            let _6 = parseState.GetInput(6) :?> 'gentype_args in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 130 "Parser.fsy"
                                                       StLoc _3 
                   )
# 130 "Parser.fsy"
                 : 'gentype_opcode));
|]
# 818 "Parser.fs"
let tables : FSharp.Text.Parsing.Tables<_> = 
  { reductions = _fsyacc_reductions.Value;
    endOfInputTag = _fsyacc_endOfInputTag;
    tagOfToken = tagOfToken;
    dataOfToken = _fsyacc_dataOfToken; 
    actionTableElements = _fsyacc_actionTableElements;
    actionTableRowOffsets = _fsyacc_actionTableRowOffsets;
    stateToProdIdxsTableElements = _fsyacc_stateToProdIdxsTableElements;
    stateToProdIdxsTableRowOffsets = _fsyacc_stateToProdIdxsTableRowOffsets;
    reductionSymbolCounts = _fsyacc_reductionSymbolCounts;
    immediateActions = _fsyacc_immediateActions;
    gotos = _fsyacc_gotos;
    sparseGotoTableRowOffsets = _fsyacc_sparseGotoTableRowOffsets;
    tagOfErrorTerminal = _fsyacc_tagOfErrorTerminal;
    parseError = (fun (ctxt:FSharp.Text.Parsing.ParseErrorContext<_>) -> 
                              match parse_error_rich with 
                              | Some f -> f ctxt
                              | None -> parse_error ctxt.Message);
    numTerminals = 31;
    productionToNonTerminalTable = _fsyacc_productionToNonTerminalTable  }
let engine lexer lexbuf startState = tables.Interpret(lexer, lexbuf, startState)
let modulee lexer lexbuf :  AlgoMoveTranspiler.Absyn.Module  =
    engine lexer lexbuf 0 :?> _
